skill_classes = [
        "ручное тестирование", "автоматизированное тестирование", "автотесты",
        "Python", "Selenium", "Postman", "тестовая документация",
        "тест-кейсы", "баг-репорты", "API", "agile", "Scrum", "SQL", "Java", "Cypress",
        "Docker", "Kubernetes", "Terraform", "Linux", "Prometheus", "Grafana", "CI/CD",
        "Ansible", "Jenkins", "GitLab CI", "CircleCI", "GitHub Actions", "AWS CloudFormation", "Pulumi",
        "Bash", "PowerShell", "Go", "Puppet", "Chef", "Google Cloud", "Azure", "EC2", "S3", "RDS",
        "ELK Stack", "Fluentd", "Loki", "TCP/IP", "DNS", "HTTP/HTTPS", "VPN", "NoSQL", "DevSecOps",
        "HashiCorp Vault", "Git", "RESTful", "SOAP", "GraphQL", "WebSocket",
        "Kong", "NGINX", "JUnit/TestNG", "JIRA", "Bugzilla",
        "Flutter", "Dart", "Android", "iOS", "Firebase", "Hive", "SQLite", "SharedPreferences",
        "Provider", "Bloc", "Riverpod", "Clean Architecture", "MVVM",
        "Material Design", "Cupertino", "Google Maps", "Yandex Maps",
        "Fastlane", "GitFlow", "FastAPI", "Push notifications",
        "JavaScript", "TypeScript", "React", "Vue", "Next.js", "Node.js",
        "PostgreSQL", "MySQL", "MongoDB", "Django"
    ]

skill_aliases = {
        "Python": ["python", "питон"],
        "FastAPI": ["fastapi", "fast api"],
        "Flutter": ["flutter"],
        "Dart": ["dart"],
        "Android": ["android"],
        "iOS": ["ios"],
        "Firebase": ["firebase"],
        "Hive": ["hive"],
        "SQLite": ["sqlite"],
        "SharedPreferences": ["sharedpreferences", "shared preferences"],
        "Provider": ["provider"],
        "Bloc": ["bloc"],
        "Riverpod": ["riverpod"],
        "Clean Architecture": ["clean architecture"],
        "MVVM": ["mvvm"],
        "Material Design": ["material design"],
        "Cupertino": ["cupertino"],
        "Google Maps": ["google maps"],
        "Yandex Maps": ["yandex maps"],
        "Fastlane": ["fastlane"],
        "GitFlow": ["gitflow", "git flow"],
        "Push notifications": ["push", "push-уведомления", "пуш"],
        "RESTful": ["rest api", "rest"],
        "GraphQL": ["graphql"],
        "WebSocket": ["websocket", "web socket"],
        "CI/CD": ["ci/cd", "ci cd", "continuous integration"],
        "Git": ["git"],
        "Docker": ["docker"],
        "Kubernetes": ["kubernetes", "k8s"],
        "Terraform": ["terraform"],
        "Linux": ["linux"],
        "Prometheus": ["prometheus"],
        "Grafana": ["grafana"],
        "Ansible": ["ansible"],
        "Jenkins": ["jenkins"],
        "GitLab CI": ["gitlab ci"],
        "GitHub Actions": ["github actions"],
        "AWS CloudFormation": ["cloudformation", "aws cloudformation"],
        "PostgreSQL": ["postgres", "postgresql"],
        "MySQL": ["mysql"],
        "MongoDB": ["mongodb"],
        "Django": ["django"],
        "Node.js": ["node.js", "nodejs", "node js"],
        "JavaScript": ["javascript", "js"],
        "TypeScript": ["typescript", "ts"],
        "React": ["react"],
        "Vue": ["vue"],
        "Next.js": ["next.js", "nextjs", "next"],
        "PostgreSQL": ["postgresql", "postgres"],
        "MySQL": ["mysql"],
        "MongoDB": ["mongodb"],
        "SQL": ["sql"],
        "NoSQL": ["nosql"],
        "Agile": ["agile"],
        "Scrum": ["scrum"],
        "TypeScript": ["typescript", "ts"],
        "JavaScript": ["javascript", "js"],
        "React": ["react"],
        "Vue": ["vue"],
        "Next.js": ["next", "next.js"],
    }

quality_classes = [
        "аккуратность", "внимание к деталям", "стремление к качеству",
        "анализ", "ответственность", "коммуникабельность", "инициативность",
        "быстрая обучаемость", "командная работа", "системность",
        "находчивость", "оперативность", "организованность", "наблюдательность",
        "решительность", "усердие", "дисциплинированность", "терпеливость",
        "усидчивость", "скрупулезность", "гибкость", "стрессоустойчивость",
        "обучаемость", "аналитическое мышление", "внимательность к деталям",
        "способность к самообучению", "клиентоориентированный подход", "критическое мышление",
        "проактивность", "самостоятельность", "лидерство"
    ]

quality_aliases = {
        "аккуратность": ["аккуратный", "аккуратность"],
        "внимание к деталям": ["внимателен к деталям", "внимательность", "attention to detail"],
        "коммуникабельность": ["коммуникабельный", "умею общаться"],
        "инициативность": ["инициативный", "проактивный"],
        "ответственность": ["ответственный"],
        "проактивность": ["проактивный", "инициативность"],
        "самостоятельность": ["самостоятельный"],
        "лидерство": ["лидерские качества", "лидер"],
    }